# Data

Source, scraping method, cleanup, etc.

## Snippet of Sample Data

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("data/collegedata_normalized.csv", index_col=0)
df.head(10)

,studentID,classrank,admissionstest,AP,averageAP,SATsubject,GPA,GPA_w,program,schooltype,...,alumni,outofstate,acceptStatus,acceptProb,name,acceptrate,size,public,finAidPct,instatePct
0,S50C3UECT8,NaN,0.838909,7,1.067927,0.323654,-0.188104,0.059072,Biomedical engineering,0,...,0,0,1,NaN,Rice,0.151,6621,0,0,0
1,GBWZQQRBEV,NaN,0.666993,7,0.661638,-0.440897,0.493061,0.398012,Classics,0,...,0,1,1,NaN,Rice,0.151,6621,0,0,0
2,MXXLWO1HQ2,NaN,0.208552,0,NaN,0.323654,0.395752,-1.035963,Biological Science,1,...,0,1,0,NaN,Rice,0.151,6621,0,0,0
3,5KSL7C8SLZ,NaN,1.297350,7,0.864783,1.088204,0.103824,-0.384156,Physics,1,...,0,1,0,NaN,Rice,0.151,6621,0,0,0
4,RQWLNGGZ49,NaN,0.323162,1,-0.354087,-0.440897,0.541716,NaN,NaN,1,...,0,1,1,NaN,Rice,0.151,6621,0,0,0
5,A7WDLWR2VM,NaN,0.323162,0,NaN,-0.440897,0.784989,NaN,Political Science,1,...,0,1,NaN,NaN,Rice,0.151,6621,0,0,0
6,CECT9K8GDY,NaN,0.724298,0,NaN,-0.440897,0.298443,0.215506,Computer Science,0,...,0,1,0,NaN,Rice,0.151,6621,0,0,0
7,9PM1B51CXG,NaN,-2.542098,3,-0.828092,-0.440897,-0.674650,-0.305940,NaN,0,...,0,1,0,NaN,Rice,0.151,6621,0,0,0
8,G14LB2SV7O,NaN,-0.020669,7,-0.354087,-1.969998,0.493061,-0.983819,Business,0,...,0,0,0,NaN,Rice,0.151,6621,0,0,0
9,PSBRN09QGH,NaN,-0.135280,4,0.001416,-0.440897,0.784989,1.779843,Computer Science,0,...,0,1,1,NaN,Rice,0.151,6621,0,0,0